py3plug-fd-postgres systemtest: remove "BROKEN" label
The test was marked broken when the plugin was using psycopg2, but now
we use pg8000 so we want to enable it again if all requirements are met.

Also we allow python >= 3.10 to be used as we now avoid the problems
arising from the fact that the stat time filds are floats instead of
ints:

> mystatp.st_atime = statp.st_atime
> TypeError: 'float' object cannot be interpreted as an integer