"list log" on postgresql needs an alias for subquery
ERROR:  subquery in FROM must have an alias
LINE 1: SELECT Time, LogText FROM (SELECT * FROM Log ORDER BY Log.Lo...
                                  ^
                                  HINT:  For example, FROM (SELECT ...)
                                  [AS] foo.

this commit adds a alias to the subquery

Also, we specify the columns we ask for instead of using an asterisk and
also get the LogId so that the Webui can sort on it.