plugins: Fix typo in postgresql plugin
This is a typo introduced in 0901b6f6613f05e47fc10b431952960e0ac6654d
The parentheses are only used to group the string concatenation and
should not contain a comma. The error results in this error message:

> Fatal error: bareosfd: Traceback (most recent call last):
>  File "/usr/lib/bareos/plugins/BareosFdWrapper.py", line 94, in
>    restore_object_data
>    return bareos_fd_plugin_object.restore_object_data(rop)
>  File "/usr/lib/bareos/plugins/bareos-fd-postgresql.py", line 1546,
>   in restore_object_data
>    bareosfd.DebugMessage(
> TypeError: BareosDebugMessage() argument 2 must be str or None, not
>  tuple

and a failed backup job.