Fix bug for PydanticSchemaGenerationError in rest_api
This patch locks down the pip package version to prevent the backward
compatibility problem from pydantic 2.x.

Since pydantic 2.x has been released, users will see the following
error without this patch:

pydantic.errors.PydanticSchemaGenerationError: Unable to generate
pydantic-core schema for <class 'bareos_restapi.models.bareosACL'>. Set
`arbitrary_types_allowed=True` in the model_config to ignore this error
or implement `__get_pydantic_core_schema__` on your type to fully
support it.