dedup: Fix missmatching types of config and fvec
This fixes the following error while compiling bareos for 32bit:

> core/src/stored/backends/dedupable/volume.cc: In constructor ‘dedup::data::data(dedup::{anonymous}::open_context, const dedup::config&)’:
> core/src/stored/backends/dedupable/volume.cc:231:61: error: narrowing conversion of ‘(uint64_t)bf.dedup::config::block_file::End’ from ‘uint64_t’ {aka ‘long long unsigned int’} to ‘dedup::fvec<dedup::block>::size_type’ {aka ‘unsigned int’} [-Werror=narrowing]
>   231 |   blocks = decltype(blocks){ctx.read_only, bfd.fileno(), bf.End};
>       |                                                          ~~~^~~
> core/src/stored/backends/dedupable/volume.cc:232:59: error: narrowing conversion of ‘(uint64_t)pf.dedup::config::part_file::End’ from ‘uint64_t’ {aka ‘long long unsigned int’} to ‘dedup::fvec<dedup::part>::size_type’ {aka ‘unsigned int’} [-Werror=narrowing]
>   232 |   parts = decltype(parts){ctx.read_only, pfd.fileno(), pf.End};
>       |                                                        ~~~^~~

The types of config::block_file::End and config::part_file::End are not
the same as fvec<block>::size_type or fvec<part>::size_type for 32bit, beacuse
size_t is not uint64_t.

This change does not change the types of the structures, because these values
are serialized on the volume.