contrib: media_vault use scriptdir and add python call
Having the shebang `/usr/bin/env python3` replaced during packaging
operation can lead the script to emit a fatal error.
Error: missing module please install: No module named 'configargparse')

We now change the helper to always call python3 without any path,
so venv call will be respected and associated modules resolvable.

Documentation has been updated to easy copy and paste of intructions,
from packaged installation by using defaultconfigs directory.

Fix bareos/bareos#2690

+ fix volstatus update

The code will now update correctly a volume status from Append
to Used when Append is selectable. (as described in the configuration
file).
Volume updated will be visible in the exported list of media.

In case the user want to have its volume status updated to Archive
all volumes will be updated.

+ media_vault README

- add comment for helper
- apply placeholders and quotes
- improve comment about venv path
- use gh syntax for note, warning

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>
Co-authored-by: Sebastian Sura <124262655+sebsura@users.noreply.github.com>