When the record contains a starttime of '0000-00-00 00:00:00' the script breaks. To avoid this a additional where clause is given
Traceback (most recent call last):
  File "/etc/bareos/bareos-graphite-poller.py", line 419, in <module>
    events = getEvents(whereJobs)# Please enter the commit message for your changes. Lines starting
  File "/etc/bareos/bareos-graphite-poller.py", line 242, in getEvents# with '#' will be ignored, and an empty message aborts the commit.
    timeObject = datetime.datetime.strptime(row['starttime'], "%Y-%m-%d %H:%M:%S")# On branch master
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime# Your branch is up-to-date with 'origin/master'.
    (data_string, format))#
ValueError: time data '0000-00-00 00:00:00' does not match format '%Y-%m-%d %H:%M:%S'