Add systemtest tls-psk-identity-err1115
- Test job with Name exceeding 104 char length so jobname got truncated
  while adding the 24 char suffix .2022-06-30_12:12:12_12
- This cause tls-psk authentification between fd and sd to failed with
  Fatal error: Connect failure: ERR=error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
  Fatal error: Bad response to Storage command: wanted 2000 OK storage, got 2902 Bad storage
  Fatal error: Director's comm line to SD dropped.

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>