migration: Mention that job resource must exist.
The attempt to migrate a job whose job resource has been removed from
the director configuration fails with an error like

        Fatal error: Previous Job resource not found for "rur_system_job"

It is not obvious that the job resource is required to migrate a
job, so this commit adds a new item for this fact in the "Important
Migration Considerations" bullet list.