core: Fix compile errors on GCC 14
Starting in GCC 14, it will no longer include <algorithm> by default,
resulting in compile errors for various projects.

https://gcc.gnu.org/gcc-14/porting_to.html

Errors:

core/src/cats/sql_get.cc:1309:42: error: cannot convert
'std::vector<std::__cxx11::basic_string<char> >::iterator' to
`const char*'

  1309 | jobids.erase(std::remove(jobids.begin(), jobids.end(),
    remove_jobid),

core/src/stored/append.cc:78:3: error: `for_each' was not declared in
this scope

 78 |   for_each(attributes_.begin(), attributes_.end(),

core/src/dird/ua_prune.cc:897:27: error: `remove_if' is not a member
of `std'; did you mean `remove_cv'?

  897 |     prune_list.erase(std::remove_if(prune_list.begin(),
     prune_list.end(),

Signed-off-by: Christopher Fore <csfore@posteo.net>
(cherry picked from commit 3907be7ff9700d0328198b47c58885f5ec56546c)